{"url": "https://api.github.com/repos/datalad/datalad/issues/2005", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/2005/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/2005/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/2005/events", "html_url": "https://github.com/datalad/datalad/issues/2005", "id": 277769268, "node_id": "MDU6SXNzdWUyNzc3NjkyNjg=", "number": 2005, "title": "datalad create-sibling-github doesn't support oauth", "user": {"login": "mvdoc", "id": 6150554, "node_id": "MDQ6VXNlcjYxNTA1NTQ=", "avatar_url": "https://avatars.githubusercontent.com/u/6150554?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mvdoc", "html_url": "https://github.com/mvdoc", "followers_url": "https://api.github.com/users/mvdoc/followers", "following_url": "https://api.github.com/users/mvdoc/following{/other_user}", "gists_url": "https://api.github.com/users/mvdoc/gists{/gist_id}", "starred_url": "https://api.github.com/users/mvdoc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mvdoc/subscriptions", "organizations_url": "https://api.github.com/users/mvdoc/orgs", "repos_url": "https://api.github.com/users/mvdoc/repos", "events_url": "https://api.github.com/users/mvdoc/events{/privacy}", "received_events_url": "https://api.github.com/users/mvdoc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-11-29T14:14:25Z", "updated_at": "2019-12-18T20:44:45Z", "closed_at": "2019-12-18T20:44:45Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### What is the problem?\r\n\r\nBecause I have two-factor authentication on (see also #2004), I had to set up a personal access token. I seem to have everything set up correctly, but when I do `datalad create-sibling-github reponame` it still asks me for username and password, and then fails. \r\n\r\nFrom playing around a bit with the code, it seems that it asks me for user and password here https://github.com/datalad/datalad/blob/33b590557d87eb42ded4821319757e03fcda5121/datalad/distribution/create_sibling_github.py#L85-L90 \r\n\r\neven though `github_login` is set to the token\r\n\r\n```\r\n(datalad) contematto@head1 /data/famface/openfmri/data (master) $ datalad create-sibling-github famface_data\r\n> /home/contematto/github/datalad/datalad/distribution/create_sibling_github.py(79)_get_github_entity()\r\n-> creds = cred()\r\n(Pdb) l\r\n 74                     cred.enter_new(\r\n 75                         user=github_login,\r\n 76                         password=github_passwd)\r\n 77             # now we should really have it\r\n 78             import pdb; pdb.set_trace()\r\n 79  ->         creds = cred()\r\n 80             github_login = creds['user']\r\n 81             github_passwd = creds['password']\r\n 82\r\n 83         if not github_login:\r\n 84             raise gh.BadCredentialsException(403, 'no login specified')\r\n(Pdb) p github_login\r\n'XXXXXXXXXXXXXXXXXXXXXXa43cde86'\r\n```\r\n\r\nand then this happens\r\n\r\n```\r\n(Pdb) c\r\nYou need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access\r\npassword:\r\nYou need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access\r\npassword (repeat):\r\n> /home/contematto/github/datalad/datalad/distribution/create_sibling_github.py(93)_get_github_entity()\r\n-> try:\r\n(Pdb) c\r\n[WARNING] Authentication failed, deleting stored credential github\r\n[ERROR  ] 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} [Requester.py:__check:180] (BadCredentialsException)\r\n```\r\n\r\n#### What version of DataLad are you using (run `datalad --version`)? \r\n\r\ndatalad 0.9.1.dev432\r\n", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/2005/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/2005/timeline", "performed_via_github_app": null}