{"url": "https://api.github.com/repos/datalad/datalad/issues/2058", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/2058/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/2058/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/2058/events", "html_url": "https://github.com/datalad/datalad/issues/2058", "id": 285308317, "node_id": "MDU6SXNzdWUyODUzMDgzMTc=", "number": 2058, "title": "aggregate-metadata breaks search", "user": {"login": "kskyten", "id": 4163878, "node_id": "MDQ6VXNlcjQxNjM4Nzg=", "avatar_url": "https://avatars.githubusercontent.com/u/4163878?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kskyten", "html_url": "https://github.com/kskyten", "followers_url": "https://api.github.com/users/kskyten/followers", "following_url": "https://api.github.com/users/kskyten/following{/other_user}", "gists_url": "https://api.github.com/users/kskyten/gists{/gist_id}", "starred_url": "https://api.github.com/users/kskyten/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kskyten/subscriptions", "organizations_url": "https://api.github.com/users/kskyten/orgs", "repos_url": "https://api.github.com/users/kskyten/repos", "events_url": "https://api.github.com/users/kskyten/events{/privacy}", "received_events_url": "https://api.github.com/users/kskyten/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-01-01T13:49:13Z", "updated_at": "2018-02-20T05:35:34Z", "closed_at": "2018-02-20T05:35:34Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### What is the problem?\r\nI got the error:\r\n`type object got multiple values for keyword argument 'type' [search.py:_get_search_index:379] (TypeError) `\r\n#### What steps will reproduce the problem?\r\n```shell\r\n(datalad) \u279c  /tmp mkdir metadatarepo \r\n(datalad) \u279c  /tmp cd metadatarepo \r\n(datalad) \u279c  metadatarepo datalad create\r\n[INFO   ] Creating a new annex repo at /tmp/metadatarepo \r\ncreate(ok): /tmp/metadatarepo (dataset)                                                             \r\n(datalad) \u279c  metadatarepo git:(master) git config --file .datalad/config --add datalad.metadata.nativetype image\r\n(datalad) \u279c  metadatarepo git:(master) \u2717 cp ../pics/cat1.jpg .\r\n(datalad) \u279c  metadatarepo git:(master) \u2717 datalad add cat1.jpg \r\nadd(ok): /tmp/metadatarepo/cat1.jpg (file)                                                                                                                                                                                                                               \r\nsave(ok): /tmp/metadatarepo (dataset)\r\naction summary:\r\n  add (ok: 1)\r\n  save (ok: 1)\r\n(datalad) \u279c  metadatarepo git:(master) \u2717 datalad aggregate-metadata                                        \r\n[INFO   ] Aggregate metadata for dataset /tmp/metadatarepo \r\n[INFO   ] Update aggregate metadata in dataset at: /tmp/metadatarepo \r\naggregate_metadata(ok): /tmp/metadatarepo (dataset)                                                                                                                                                                                                                      \r\n[INFO   ] Attempting to save 6 files/datasets \r\nsave(ok): /tmp/metadatarepo (dataset)                                                                                                                                                                                                                                    \r\naction summary:\r\n  aggregate_metadata (ok: 1)\r\n  save (ok: 1)\r\n(datalad) \u279c  metadatarepo git:(master) \u2717 datalad search --show-keys\r\n[INFO   ] Building search index \r\n[INFO   ] Scanning for metadata keys \r\n[ERROR  ] type object got multiple values for keyword argument 'type' [search.py:_get_search_index:379] (TypeError) \r\n(datalad) \u279c  metadatarepo git:(master) \u2717 datalad search cat\r\n[INFO   ] Rebuilding search index \r\n[INFO   ] Scanning for metadata keys \r\n[ERROR  ] type object got multiple values for keyword argument 'type' [search.py:_get_search_index:379] (TypeError) \r\n```\r\n#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?\r\ndatalad 0.9.1.dev548", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/2058/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/2058/timeline", "performed_via_github_app": null}