{"url": "https://api.github.com/repos/datalad/datalad/issues/2244", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/2244/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/2244/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/2244/events", "html_url": "https://github.com/datalad/datalad/issues/2244", "id": 301158712, "node_id": "MDU6SXNzdWUzMDExNTg3MTI=", "number": 2244, "title": "Unicode issue with PY3.5", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-02-28T19:49:25Z", "updated_at": "2020-01-09T21:12:11Z", "closed_at": "2020-01-09T21:12:10Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "PY3.5 test on container from #2242 fails with unicode error\r\n\r\n```\r\n======================================================================\r\nERROR: datalad.tests.test_config.test_something\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.5/dist-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py\", line 492, in newfunc\r\n    create_tree(d, tree, archives_leading_dir=archives_leading_dir)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py\", line 174, in create_tree\r\n    create_tree(full_name, load, archives_leading_dir=archives_leading_dir)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py\", line 174, in create_tree\r\n    create_tree(full_name, load, archives_leading_dir=archives_leading_dir)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py\", line 182, in create_tree\r\n    f.write(load)\r\nUnicodeEncodeError: 'ascii' codec can't encode character '\\u306e' in position 94: ordinal not in range(128)\r\n\r\n======================================================================\r\nERROR: datalad.tests.test_utils.test_read_csv_lines_tsv_unicode\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.5/dist-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py\", line 629, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/tests/test_utils.py\", line 914, in test_read_csv_lines_tsv_unicode\r\n    list(gen),\r\n  File \"/usr/local/lib/python3.5/dist-packages/datalad/utils.py\", line 1455, in read_csv_lines\r\n    for row in csv_reader:\r\n  File \"/usr/lib/python3.5/encodings/ascii.py\", line 26, in decode\r\n    return codecs.ascii_decode(input, self.errors)[0]\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 9: ordinal not in range(128)\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/2244/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/2244/timeline", "performed_via_github_app": null}