{"url": "https://api.github.com/repos/datalad/datalad/issues/3198", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3198/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3198/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3198/events", "html_url": "https://github.com/datalad/datalad/issues/3198", "id": 417666183, "node_id": "MDU6SXNzdWU0MTc2NjYxODM=", "number": 3198, "title": "Test failure due to version string \"0.12.0rc1\"", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-03-06T07:47:26Z", "updated_at": "2019-03-07T23:59:10Z", "closed_at": "2019-03-07T23:46:58Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "0.12.0rc1 release broke test assumptions, or was a mistake. @yarikoptic please clarify whether this test can simply be deleted? It did not show up before the merge, and failure only after a merge seems not useful.\r\n\r\n```\r\n======================================================================\r\nFAIL: datalad.tests.test_version.test__version__\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py\", line 197, in runTest\r\n    self.test(*self.arg)\r\n  File \"/home/travis/build/datalad/datalad/datalad/tests/test_version.py\", line 69, in test__version__\r\n    assert_greater(lv_changelog_version, lv__version__)\r\nAssertionError: LooseVersion ('0.12.0rc1') not greater than LooseVersion ('0.12.0rc1.dev1')\r\n```\r\n\r\n#3197 ", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3198/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3198/timeline", "performed_via_github_app": null}