{"url": "https://api.github.com/repos/datalad/datalad/issues/3287", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3287/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3287/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3287/events", "html_url": "https://github.com/datalad/datalad/issues/3287", "id": 428751819, "node_id": "MDU6SXNzdWU0Mjg3NTE4MTk=", "number": 3287, "title": "appveyor fails to annex init for v6 in test_add_recursive", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-04-03T12:56:15Z", "updated_at": "2019-04-22T15:38:32Z", "closed_at": "2019-04-22T15:38:32Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "Fresh failure on appveyor https://ci.appveyor.com/project/mih/datalad/builds/23566971/job/k617r2yxoprmg547, smells like just some instability in annex since none other test fails on this basic operation?\r\n\r\n```\r\n======================================================================\r\nERROR: datalad.core.local.tests.test_save.test_add_recursive\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 607, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\contextlib.py\", line 77, in __exit__\r\n    self.gen.throw(type, value, traceback)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\utils.py\", line 1598, in make_tempfile\r\n    yield filename\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 607, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\core\\local\\tests\\test_save.py\", line 486, in test_add_recursive\r\n    parent = Dataset(path).rev_create()\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\distribution\\dataset.py\", line 553, in apply_func\r\n    return f(**kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 492, in eval_func\r\n    return return_func(generator_func)(*args, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 480, in return_func\r\n    results = list(results)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 429, in generator_func\r\n    result_renderer, result_xfm, _result_filter, **_kwargs):\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 522, in _process_results\r\n    for res in results:\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\core\\local\\create.py\", line 313, in __call__\r\n    fake_dates=fake_dates\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\support\\repo.py\", line 146, in __call__\r\n    instance = type.__call__(cls, *new_args, **new_kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\support\\annexrepo.py\", line 256, in __init__\r\n    self._init(version=version, description=description)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\support\\annexrepo.py\", line 1157, in _init\r\n    annex_options=opts)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\support\\annexrepo.py\", line 981, in _run_annex_command\r\n    env=env, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\support\\gitrepo.py\", line 1866, in _run_command_files_split\r\n    *args, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\cmd.py\", line 691, in run\r\n    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\cmd.py\", line 550, in run\r\n    raise CommandError(text_type(cmd), msg, status, out[0], out[1])\r\ndatalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6']' failed with exitcode 1\r\nFailed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6'] under 'C:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_y9ho49u4'. Exit code=1.\r\n```", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3287/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3287/timeline", "performed_via_github_app": null}