{"url": "https://api.github.com/repos/datalad/datalad/issues/3634", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3634/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3634/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3634/events", "html_url": "https://github.com/datalad/datalad/issues/3634", "id": 487749216, "node_id": "MDU6SXNzdWU0ODc3NDkyMTY=", "number": 3634, "title": "datalad.distribution.tests.test_get failures on real win10/conda", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 188141023, "node_id": "MDU6TGFiZWwxODgxNDEwMjM=", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-windows", "name": "platform-windows", "color": "0052cc", "default": false, "description": "Issue concerned with Windows"}, {"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-08-31T09:05:44Z", "updated_at": "2019-09-27T05:41:36Z", "closed_at": "2019-09-27T05:41:36Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "The appveyor environment is supercharged in many ways. Here is a glimpse of reality starting from https://github.com/datalad-handbook/book/issues/132:\r\n\r\n```\r\n> python -m nose datalad.distribution.tests.test_get\r\n======================================================================\r\nFAIL: datalad.distribution.tests.test_get.test_get_recurse_dirs\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 1228, in assert_status\r\n    assert_in(r['status'], label)\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\unittest\\case.py\", line 1106, in assertIn\r\n    self.fail(self._formatMessage(msg, standardMsg))\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\unittest\\case.py\", line 680, in fail\r\n    raise self.failureException(msg)\r\nAssertionError: 'notneeded' not found in ['ok']\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 434, in newfunc\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 607, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\distribution\\tests\\test_get.py\", line 229, in test_get_recurse_dirs\r\n    assert_status('ok', result)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 1234, in assert_status\r\n    dumps(results, indent=1, default=lambda x: str(x))))\r\nAssertionError: Test 4/4: expected status ['ok'] not found in:\r\n[\r\n {\r\n  \"type\": \"file\",\r\n  \"refds\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\",\r\n  \"status\": \"ok\",\r\n  \"path\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\\\\subdir/subsubdir/file4.txt\",\r\n  \"action\": \"get\",\r\n  \"annexkey\": \"MD5E-s9--437b930db84b8079c2dd804a71936b5f.txt\",\r\n  \"message\": \"from origin...\"\r\n },\r\n {\r\n  \"type\": \"file\",\r\n  \"refds\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\",\r\n  \"status\": \"ok\",\r\n  \"path\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\\\\subdir/file2.txt\",\r\n  \"action\": \"get\",\r\n  \"annexkey\": \"MD5E-s14--6c7ba9c5a141421e1c03cb9807c97c74.txt\",\r\n  \"message\": \"from origin...\"\r\n },\r\n {\r\n  \"type\": \"file\",\r\n  \"refds\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\",\r\n  \"status\": \"ok\",\r\n  \"path\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\\\\subdir/subsubdir/file3.txt\",\r\n  \"action\": \"get\",\r\n  \"annexkey\": \"MD5E-s30--c22e53b13855f9e313a02bcb7c26a7cc.txt\",\r\n  \"message\": \"from origin...\"\r\n },\r\n {\r\n  \"action\": \"get\",\r\n  \"path\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\\\\subdir\",\r\n  \"type\": \"directory\",\r\n  \"refds\": \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\",\r\n  \"status\": \"notneeded\",\r\n  \"message\": [\r\n   \"nothing to get from %s\",\r\n   \"C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_n06xb8w0\\\\subdir\"\r\n  ]\r\n }\r\n]\r\n\r\n======================================================================\r\nFAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 607, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 607, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"c:\\users\\mih\\code\\datalad\\datalad\\distribution\\tests\\test_get.py\", line 87, in test_get_flexible_source_candidates_for_submodule\r\n    eq_(f(clone, 'sub'), [t + '/sub'])\r\nAssertionError: ['C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_et9vdsui\\\\sub'] != ['C:\\\\Users\\\\mih\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_et9vdsui/sub']\r\n\r\n----------------------------------------------------------------------\r\nRan 13 tests in 241.061s\r\n\r\nFAILED (SKIP=5, failures=2)\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3634/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3634/timeline", "performed_via_github_app": null}