{"url": "https://api.github.com/repos/datalad/datalad/issues/3932", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3932/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3932/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3932/events", "html_url": "https://github.com/datalad/datalad/issues/3932", "id": 538388329, "node_id": "MDU6SXNzdWU1MzgzODgzMjk=", "number": 3932, "title": "`create` does not automatically recover after botched `annex init` on \"broken\" NFS setup", "user": {"login": "nhjjreuter", "id": 24777116, "node_id": "MDQ6VXNlcjI0Nzc3MTE2", "avatar_url": "https://avatars.githubusercontent.com/u/24777116?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nhjjreuter", "html_url": "https://github.com/nhjjreuter", "followers_url": "https://api.github.com/users/nhjjreuter/followers", "following_url": "https://api.github.com/users/nhjjreuter/following{/other_user}", "gists_url": "https://api.github.com/users/nhjjreuter/gists{/gist_id}", "starred_url": "https://api.github.com/users/nhjjreuter/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nhjjreuter/subscriptions", "organizations_url": "https://api.github.com/users/nhjjreuter/orgs", "repos_url": "https://api.github.com/users/nhjjreuter/repos", "events_url": "https://api.github.com/users/nhjjreuter/events{/privacy}", "received_events_url": "https://api.github.com/users/nhjjreuter/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 63778595, "node_id": "MDU6TGFiZWw2Mzc3ODU5NQ==", "url": "https://api.github.com/repos/datalad/datalad/labels/wontfix", "name": "wontfix", "color": "ffffff", "default": true, "description": "Issue is unlikely to be addressed"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-12-16T12:40:52Z", "updated_at": "2019-12-16T14:19:55Z", "closed_at": "2019-12-16T14:15:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to create a datalad data set on an existing folder using `datalad create --force` and get the below error.\r\n\r\n> user@server:/path/to/data$ datalad create --force\r\n> [INFO   ] Creating a new annex repo at /path/to/data \r\n> CommandError: command '['git-annex', 'add', '--json', '--json-error-messages', '-c', 'annex.largefiles=nothing', '--include-dotfiles', '--', '.gitattributes']' failed with exitcode 1\r\n> Failed to run ['git-annex', 'add', '--json', '--json-error-messages', '-c', 'annex.largefiles=nothing', '--include-dotfiles', '--', '.gitattributes'] under '/path/to/data'. Exit code=1.\r\n> git-annex: First run: git-annex init\r\n\r\n`$ datalad --version`\r\n`datalad 0.12.0rc6`\r\n\r\nOperating system: posix linux 4.15.0-65-generic, version 74-Ubuntu SMP, distribution Ubuntu/18.04/bionic\r\n\r\ngit-annex version: 7.20190219+git191-g2d6a364d4-1~ndall+1\r\n\r\nThe problem is solved by manually running `git-annex init` followed by `datalad create --force`, but I think datalad should not be getting this error.", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3932/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3932/timeline", "performed_via_github_app": null}