{"url": "https://api.github.com/repos/datalad/datalad/issues/4333", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4333/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4333/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4333/events", "html_url": "https://github.com/datalad/datalad/issues/4333", "id": 586770790, "node_id": "MDU6SXNzdWU1ODY3NzA3OTA=", "number": 4333, "title": "TST: datalad.core.distributed.tests.test_clone.test_clone_datasets_root", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 63778590, "node_id": "MDU6TGFiZWw2Mzc3ODU5MA==", "url": "https://api.github.com/repos/datalad/datalad/labels/severity-normal", "name": "severity-normal", "color": "ff8888", "default": false, "description": "standard severity"}, {"id": 188141023, "node_id": "MDU6TGFiZWwxODgxNDEwMjM=", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-windows", "name": "platform-windows", "color": "0052cc", "default": false, "description": "Issue concerned with Windows"}, {"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-03-24T08:07:33Z", "updated_at": "2020-11-06T16:09:40Z", "closed_at": "2020-11-06T16:09:40Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "```\r\n======================================================================\r\nERROR: datalad.core.distributed.tests.test_clone.test_clone_datasets_root\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 166, in newfunc\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\support\\vcr_.py\", line 90, in wrapper\r\n    return t(*args, **kwargs)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 518, in newfunc\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\core\\distributed\\tests\\test_clone.py\", line 142, in test_clone_datasets_root\r\n    res = clone(\"///\", on_failure='ignore', result_xfm=None, return_type='list')\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\wrapt\\wrappers.py\", line 564, in __call__\r\n    args, kwargs)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\interface\\utils.py\", line 492, in eval_func\r\n    return return_func(generator_func)(*args, **kwargs)\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\wrapt\\wrappers.py\", line 564, in __call__\r\n    args, kwargs)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\interface\\utils.py\", line 480, in return_func\r\n    results = list(results)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\interface\\utils.py\", line 411, in generator_func\r\n    allkwargs):\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\interface\\utils.py\", line 527, in _process_results\r\n    for res in results:\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\core\\distributed\\clone.py\", line 285, in __call__\r\n    cfg=None if ds is None else ds.config,\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\core\\distributed\\clone.py\", line 384, in clone_dataset\r\n    or get_local_file_url(track_url, compatibility='git') == src \\\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\support\\network.py\", line 922, in get_local_file_url\r\n    path = Path(fname).resolve()\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\pathlib.py\", line 1144, in resolve\r\n    s = self._flavour.resolve(self, strict=strict)\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\pathlib.py\", line 201, in resolve\r\n    s = self._ext_to_normal(_getfinalpathname(s))\r\nOSError: [WinError 123] Die Syntax f\u00fcr den Dateinamen, Verzeichnisnamen oder die Datentr\u00e4gerbezeichnung ist falsch: 'http:\\\\datasets-tests.datalad.org\\\\.git'\r\n```\r\n\r\nLegitimate URL gets butchered by replacing slashes with backslashes.", "closed_by": {"login": "kyleam", "id": 1297788, "node_id": "MDQ6VXNlcjEyOTc3ODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1297788?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyleam", "html_url": "https://github.com/kyleam", "followers_url": "https://api.github.com/users/kyleam/followers", "following_url": "https://api.github.com/users/kyleam/following{/other_user}", "gists_url": "https://api.github.com/users/kyleam/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyleam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyleam/subscriptions", "organizations_url": "https://api.github.com/users/kyleam/orgs", "repos_url": "https://api.github.com/users/kyleam/repos", "events_url": "https://api.github.com/users/kyleam/events{/privacy}", "received_events_url": "https://api.github.com/users/kyleam/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4333/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4333/timeline", "performed_via_github_app": null}