{"url": "https://api.github.com/repos/datalad/datalad/issues/4812", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4812/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4812/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4812/events", "html_url": "https://github.com/datalad/datalad/issues/4812", "id": 675155173, "node_id": "MDU6SXNzdWU2NzUxNTUxNzM=", "number": 4812, "title": "\"EASY\" install entry points are generated", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2020-08-07T17:10:45Z", "updated_at": "2020-08-08T04:20:34Z", "closed_at": "2020-08-08T04:20:33Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "With https://github.com/datalad/datalad/pull/4695 (against master, `maint` is not effected) we switched to use entry points generated by pip under assumption that with recent versions of pip we would get entry points which would not use `from pkg_resources import load_entry_point`.\r\n\r\nAfter that tests of master within https://github.com/datalad/datalad-extensions/ started to fail on our unittest check that there is no EASY in entry point script:\r\n\r\nhttps://pipelines.actions.githubusercontent.com/2UPlDxaVvvbkeFX4btxWorCjpJvj40zvWY5ogH2yZibhOMcU7O/_apis/pipelines/1/runs/1215/signedlogcontent/18?urlExpires=2020-08-07T17%3A01%3A07.5945328Z&urlSigningMethod=HMACV1&urlSignature=Vt72Dj9EnZwCagKG%2BoSyMTMDg2VCIx2jvarg6WqHogw%3D\r\n\r\n```\r\n2020-08-07T02:39:55.6249423Z ======================================================================\r\n2020-08-07T02:39:55.6249720Z FAIL: datalad.cmdline.tests.test_main.test_script_shims\r\n2020-08-07T02:39:55.6250546Z ----------------------------------------------------------------------\r\n2020-08-07T02:39:55.6250923Z Traceback (most recent call last):\r\n2020-08-07T02:39:55.6251824Z   File \"/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n2020-08-07T02:39:55.6252252Z     self.test(*self.arg)\r\n2020-08-07T02:39:55.6253333Z   File \"/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/datalad/cmdline/tests/test_main.py\", line 190, in test_script_shims\r\n2020-08-07T02:39:55.6254187Z     assert_not_in('EASY', content) # NOTHING easy should be there\r\n2020-08-07T02:39:55.6255195Z AssertionError: 'EASY' unexpectedly found in \"#!/opt/hostedtoolcache/Python/3.7.8/x64/bin/python\\n# EASY-INSTALL-ENTRY-SCRIPT: 'datalad==0.13.1','console_scripts','datalad'\\n__requires__ = 'datalad==0.13.1'\\nimport re\\nimport sys\\nfrom pkg_resources import load_entry_point\\n\\nif __name__ == '__main__':\\n    sys.argv[0] = re.sub(r'(-script\\\\.pyw?|\\\\.exe)?$', '', sys.argv[0])\\n    sys.exit(\\n        load_entry_point('datalad==0.13.1', 'console_scripts', 'datalad')()\\n    )\\n\"\r\n2020-08-07T02:39:55.6255963Z \r\n2020-08-07T02:39:55.6256905Z ----------------------------------------------------------------------\r\n2020-08-07T02:39:55.6258087Z Ran 1177 tests in 3464.796s\r\n2020-08-07T02:39:55.6258412Z \r\n```\r\n\r\nour datalad installation [code](https://github.com/datalad/datalad-extensions/blob/master/.github/workflows/build-git-annex-debianstandalone.yaml#L144) there first should upgrade pip and then proceed with installation of datalad:\r\n\r\n```\r\n          python -m pip install --upgrade pip\r\n          pip install https://github.com/datalad/datalad/archive/${commitish}.zip\r\n```\r\n\r\noutput in the log seems to support the fact that pip is first upgraded and then we proceed to the 2nd command to install datalad from github:\r\n\r\n```\r\n2020-08-07T01:41:51.7440572Z Collecting pip\r\n2020-08-07T01:41:51.7797979Z   Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)\r\n2020-08-07T01:41:51.9460441Z Installing collected packages: pip\r\n2020-08-07T01:41:51.9463847Z   Attempting uninstall: pip\r\n2020-08-07T01:41:51.9471333Z     Found existing installation: pip 20.2\r\n2020-08-07T01:41:52.0977071Z     Uninstalling pip-20.2:\r\n2020-08-07T01:41:52.1205880Z       Successfully uninstalled pip-20.2\r\n2020-08-07T01:41:52.9926046Z Successfully installed pip-20.2.1\r\n2020-08-07T01:41:53.7170964Z Collecting https://github.com/datalad/datalad/archive/master.zip\r\n2020-08-07T01:41:53.8539923Z   Downloading https://github.com/datalad/datalad/archive/master.zip (1.8 MB)\r\n```\r\n\r\nbut may be somehow because all commands come from the same \"code block\" 2nd pip invocation does not use freshly installed pip or smth like that?\r\n\r\nany ideas @jwodder on what might be happening, i.e. why entry point shim is the EASY-INSTALL one?\r\n\r\n", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4812/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4812/timeline", "performed_via_github_app": null}