{"url": "https://api.github.com/repos/datalad/datalad/issues/5593", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5593/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5593/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5593/events", "html_url": "https://github.com/datalad/datalad/issues/5593", "id": 864202512, "node_id": "MDU6SXNzdWU4NjQyMDI1MTI=", "number": 5593, "title": "datalad special remote fails with LD_LIBRARY_PATH spec within HTCondor", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2021-04-21T19:36:00Z", "updated_at": "2021-04-22T05:57:06Z", "closed_at": null, "author_association": "MEMBER", "active_lock_reason": null, "body": "I am debugging a user bug report. I have a simple job script that downloads a small text file from the HCP dataset. The HCP credentials are provided via environment variable.\r\n\r\n```sh\r\n#!/bin/sh\r\n\r\nset -e -x -u\r\n\r\nsubj=$1\r\nwdir=\"/tmp/hcp\"\r\n\r\ndatalad clone https://github.com/datalad-datasets/human-connectome-project-openaccess.git $wdir\r\ndatalad -C $wdir -l debug get HCP1200/${subj}/MNINonLinear/Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt\r\n```\r\n\r\nIf I run that script on the cluster head node, it works fine. If I run it on a compute node, same thing, all good.\r\n\r\nHere is the submit file:\r\n\r\n```\r\nuniverse       = vanilla\r\ngetenv         = True\r\nexecutable     = /home/mih/reproducer/doit.sh\r\ntransfer_executable   = yes\r\nlog = /home/mih/reproducer/logs/$(Cluster).$(Process).log\r\noutput = /home/mih/reproducer/logs/$(Cluster).$(Process).out\r\nerror = /home/mih/reproducer/logs/$(Cluster).$(Process).err\r\nqueue arguments from (\r\n  137532\r\n)\r\n```\r\n\r\nIf I submit that, all is good.\r\n\r\nHowever, if I add the follow spec to it, downloads no longer work:\r\n\r\n```\r\nenvironment = \"LD_LIBRARY_PATH=/opt/MATLAB/R2019b/runtime/glnxa64:/opt/MATLAB/R2019b/bin/glnxa64:/opt/MATLAB/R2019b/sys/os/glnxa64:/opt/MATLAB/R2019b/sys/opengl/lib/glnxa64\"\r\n```\r\n\r\nInstead of downloading, the progress is stuck at 0% and fails after a while. `datalad get` is not very informative:\r\n\r\n```\r\n[DEBUG  ] Launching process ['git', 'annex', 'get', '--json', '--json-error-messages', '--json-progress', '--debug', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', 'Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt'] \r\n[DEBUG  ] Process 37757 started \r\n[Level 5] Requested to provide version for tqdm \r\n[Level 5] Requested to provide version for tqdm \r\n[DEBUG  ] Waiting for process 37757 to complete                                            \r\n[Level 5] Read 190 bytes from 37757[stderr]                                                \r\n...\r\n[Level 5] Read 25 bytes from 37757[stderr] \r\n[DEBUG  ] Process 37757 exited with return code 1 \r\n[Level 8] Finished running ['git', 'annex', 'get', '--json', '--json-error-messages', '--json-progress', '--debug', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', 'Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt'] with status 1 \r\n[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [], 'note': 'from datalad...\\nUnable to access these remotes: datalad\\n(Note that these git remotes have annex-ignore set: origin)', 'success': False, 'input': ['Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt'], 'key': 'MD5E-s159600--144e92884f8789302700dbebe52c51dd.txt', 'error-messages': ['  Failed to download from any of 1 locations [datalad.py:_transfer:163]', '  Failed to download from any of 1 locations [datalad.py:_transfer:163]', '  Failed to download from any of 1 locations [datalad.py:_transfer:163]'], 'file': 'Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt'} \r\n[ERROR  ] Failed to download from any of 1 locations [datalad.py:_transfer:163]\r\n| Failed to download from any of 1 locations [datalad.py:_transfer:163]\r\n| Failed to download from any of 1 locations [datalad.py:_transfer:163] [get(/tmp/hcp/HCP1200/137532/MNINonLinear/Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt)] \r\n```\r\n\r\nbut `git annex get` reveals some hints:\r\n\r\n```\r\n[INFO] S3 session: Connecting to the bucket hcp-openaccess with authentication \r\n[2021-04-21 20:48:56.951971158] /usr/bin/git-annex-remote-datalad[1] --> DEBUG Failed to download url s3://hcp-openaccess/HCP_1200/137532/MNINonLinear/Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt?versionId=yeRaI0PaQOY9zAf24UshhEGvQl6EOjZ6 for key MD5E-s159600--144e92884f8789302700dbebe52c51dd.txt: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056) [ssl.py:do_handshake:1117]\r\n[2021-04-21 20:48:56.952234241] Failed to download url s3://hcp-openaccess/HCP_1200/137532/MNINonLinear/Results/rfMRI_REST1_LR/Movement_Regressors_dt.txt?versionId=yeRaI0PaQOY9zAf24UshhEGvQl6EOjZ6 for key MD5E-s159600--144e92884f8789302700dbebe52c51dd.txt: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056) [ssl.py:do_handshake:1117]\r\n[2021-04-21 20:48:56.952354812] /usr/bin/git-annex-remote-datalad[1] --> GETURLS MD5E-s159600--144e92884f8789302700dbebe52c51dd.txt shub:\r\n[2021-04-21 20:48:56.952614924] /usr/bin/git-annex-remote-datalad[1] <-- VALUE \r\n[2021-04-21 20:48:56.953424966] /usr/bin/git-annex-remote-datalad[1] --> TRANSFER-FAILURE RETRIEVE MD5E-s159600--144e92884f8789302700dbebe52c51dd.txt Failed to download from any of 1 locations [datalad.py:_transfer:163]\r\n\r\n  Failed to download from any of 1 locations [datalad.py:_transfer:163]\r\n[2021-04-21 20:48:56.956975474] process [40591] done ExitSuccess\r\n[2021-04-21 20:48:56.957444565] process [40592] done ExitSuccess\r\n\r\n  Unable to access these remotes: datalad\r\n[2021-04-21 20:48:56.959623008] process [783] chat: git [\"--git-dir=../../.git\",\"--work-tree=../..\",\"--literal-pathspecs\",\"cat-file\",\"--batch\"]\r\n[2021-04-21 20:48:56.960382969] process [784] chat: git [\"--git-dir=../../.git\",\"--work-tree=../..\",\"--literal-pathspecs\",\"cat-file\",\"--batch-check=%(objectname) %(objecttype) %(objectsize)\"]\r\n\r\n  No other repository is known to contain the file.\r\n\r\n  (Note that these git remotes have annex-ignore set: origin)\r\nfailed\r\n```\r\n\r\nRunning with the `LD_LIBRARY_PATH` setting directly, outside condor, does *not* cause the problem. I.e.\r\n\r\n```\r\nLD_LIBRARY_PATH=/opt/MATLAB/R2019b/runtime/glnxa64:/opt/MATLAB/R2019b/bin/glnxa64:/opt/MATLAB/R2019b/sys/os/glnxa64:/opt/MATLAB/R2019b/sys/opengl/lib/glnxa64 DATALAD_hcp_s3_key_id=... DATALAD_hcp_s3_secret_id=... ./doit.sh 137532\r\n```\r\n", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5593/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5593/timeline", "performed_via_github_app": null}