{"url": "https://api.github.com/repos/datalad/datalad/issues/5717", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5717/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5717/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5717/events", "html_url": "https://github.com/datalad/datalad/issues/5717", "id": 913511177, "node_id": "MDU6SXNzdWU5MTM1MTExNzc=", "number": 5717, "title": "fasteners 0.16.1 removed .acquired and thus broke datalad", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-06-07T12:48:04Z", "updated_at": "2021-06-18T13:33:48Z", "closed_at": "2021-06-18T13:33:48Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "complained upstream https://github.com/harlowja/fasteners/issues/71\r\n\r\nspotted while observing avalanche of CI failures for https://github.com/datalad/datalad/pull/5709 which should have been green.\r\n\r\ncrashes look like this\r\n```\r\n======================================================================\r\nERROR: datalad.tests.test_archives.test_ExtractedArchive\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/support/locking.py\", line 91, in lock_if_check_fails\r\n    lgr.debug(\"Acquired? lock %s: %s\", lock_filename, lock.acquired)\r\nAttributeError: '_FcntlLock' object has no attribute 'acquired'\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/tests/utils.py\", line 585, in _wrap_with_tree\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/tests/test_archives.py\", line 192, in test_ExtractedArchive\r\n    extracted_ = earchive.get_extracted_file(fpath)\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/support/archives.py\", line 427, in get_extracted_file\r\n    self.assure_extracted()\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/support/archives.py\", line 315, in assure_extracted\r\n    with lock_if_check_fails(\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/contextlib.py\", line 113, in __enter__\r\n    return next(self.gen)\r\n  File \"/tmp/dl-miniconda-1newyg4m/lib/python3.8/site-packages/datalad/support/locking.py\", line 100, in lock_if_check_fails\r\n    if lock.acquired:\r\nAttributeError: '_FcntlLock' object has no attribute 'acquired'\r\n```\r\n\r\nwe could have added upper bound for fasteners version, but I guess the best would be to look into removing use of `.acquired` -- will look into it now.", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5717/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5717/timeline", "performed_via_github_app": null}