{"url": "https://api.github.com/repos/datalad/datalad/issues/5758", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5758/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5758/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5758/events", "html_url": "https://github.com/datalad/datalad/issues/5758", "id": 927401039, "node_id": "MDU6SXNzdWU5Mjc0MDEwMzk=", "number": 5758, "title": "swarm of fails in datalad/git-annex master branch testing", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/datalad/datalad/milestones/86", "html_url": "https://github.com/datalad/datalad/milestone/86", "labels_url": "https://api.github.com/repos/datalad/datalad/milestones/86/labels", "id": 6382960, "node_id": "MDk6TWlsZXN0b25lNjM4Mjk2MA==", "number": 86, "title": "0.15.0", "description": "", "creator": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 22, "state": "open", "created_at": "2021-02-02T14:46:01Z", "updated_at": "2021-09-10T17:50:04Z", "due_on": null, "closed_at": null}, "comments": 3, "created_at": "2021-06-22T16:01:33Z", "updated_at": "2021-07-19T15:23:44Z", "closed_at": "2021-07-19T15:23:44Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "see https://github.com/datalad/git-annex/runs/2881114114?check_suite_focus=true  not yet sure what/why since we were green for https://github.com/datalad/datalad/pull/5691 PR\r\n\r\n<details>\r\n<summary>partial extract</summary> \r\n\r\n```shell\r\n======================================================================\r\nFAIL: datalad.support.tests.test_external_versions.test_external_versions_rogue_module\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 739, in _wrap_with_tempfile\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/support/tests/test_external_versions.py\", line 141, in test_external_versions_rogue_module\r\n    assert_in('pickaboo', cml.out)\r\nWarning: Error: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n-------------------- >> begin captured logging << --------------------\r\ndatalad: WARNING: Failed to import module verycustomrogue__ due to \r\n--------------------- >> end captured logging << ---------------------\r\n\r\n======================================================================\r\nFAIL: datalad.support.tests.test_github_.test__make_github_repos\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/support/tests/test_github_.py\", line 113, in test__make_github_repos\r\n    assert_in('Failed to create repository while using token 1to...: very bad status', cml.out)\r\nWarning: Error: 'Failed to create repository while using token 1to...: very bad status' not found in '[WARNING] Failed to create repository while using token 1to...: \\n'\r\n-------------------- >> begin captured logging << --------------------\r\ndatalad.support.github_: WARNING: Failed to create repository while using token 1to...: \r\n--------------------- >> end captured logging << ---------------------\r\n\r\n======================================================================\r\nFAIL: datalad.support.tests.test_sshconnector.test_ssh_manager_close_no_throw\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 739, in _wrap_with_tempfile\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/support/tests/test_sshconnector.py\", line 202, in test_ssh_manager_close_no_throw\r\n    assert_in('Failed to close a connection: oh I am so bad', cml.out)\r\nAssertionError: 'Failed to close a connection: oh I am so bad' not found in '[DEBUG] Closing 1 SSH connections...\\n[DEBUG] Failed to close a connection: \\n'\r\n-------------------- >> begin captured logging << --------------------\r\ndatalad.support.sshconnector: DEBUG: Closing 1 SSH connections...\r\ndatalad.support.sshconnector: DEBUG: Failed to close a connection: \r\n--------------------- >> end captured logging << ---------------------\r\n\r\n======================================================================\r\nFAIL: datalad.tests.test_utils.test_import_modules_fail\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/test_utils.py\", line 1098, in test_import_modules_fail\r\n    ok_startswith(failures[0], \"Fail datalad.bogus: No module\")\r\n  File \"/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 435, in ok_startswith\r\n    msg=\"String %r doesn't start with %r\" % (s, prefix))\r\nAssertionError: String 'Fail datalad.bogus: ' doesn't start with 'Fail datalad.bogus: No module'\r\n\r\n```\r\n</details>\r\n\r\nfull logs could be found on smaug:/mnt/datasets/datalad/ci/git-annex/builds/2021/06/cron-20210622/build-ubuntu.yaml-317-a1f634dc-failed and I also see lots of hits for the 'pickaboo' in the logs for #5691:\r\n\r\n```shell\r\n(tinuous-dev) datalad@smaug:/mnt/datasets/datalad/ci/logs/2021/06/08/pr/5691$ git grep 'pickaboo'\r\n3dcf2d3/github-Test on macOS-1425-failed/1_test (brew).txt:2021-06-08T12:51:55.5946970Z     assert_in('pickaboo', cml.out)\r\n3dcf2d3/github-Test on macOS-1425-failed/1_test (brew).txt:2021-06-08T12:51:55.5948100Z AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n3dcf2d3/github-Test on macOS-1425-failed/2_test (snapshot).txt:2021-06-08T13:01:34.0297150Z     assert_in('pickaboo', cml.out)\r\n3dcf2d3/github-Test on macOS-1425-failed/2_test (snapshot).txt:2021-06-08T13:01:34.0298580Z AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n3dcf2d3/github-Test on macOS-1425-failed/test (brew)/8_Run tests.txt:2021-06-08T12:51:55.5946960Z     assert_in('pickaboo', cml.out)\r\n3dcf2d3/github-Test on macOS-1425-failed/test (brew)/8_Run tests.txt:2021-06-08T12:51:55.5948090Z AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n3dcf2d3/github-Test on macOS-1425-failed/test (snapshot)/8_Run tests.txt:2021-06-08T13:01:34.0297130Z     assert_in('pickaboo', cml.out)\r\n3dcf2d3/github-Test on macOS-1425-failed/test (snapshot)/8_Run tests.txt:2021-06-08T13:01:34.0298570Z AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n588644c/appveyor-6107-failed/57k0ylu8v3p39hqb.txt:[00:37:34]     assert_in('pickaboo', cml.out)\r\n588644c/appveyor-6107-failed/57k0ylu8v3p39hqb.txt:[00:37:34] AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n588644c/appveyor-6107-failed/fvlsmm3k5y2poi8v.txt:[00:44:40]     assert_in('pickaboo', cml.out)\r\n588644c/appveyor-6107-failed/fvlsmm3k5y2poi8v.txt:[00:44:40] AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n588644c/appveyor-6107-failed/jnnx886qnxc0j47q.txt:[00:44:50]     assert_in('pickaboo', cml.out)\r\n588644c/appveyor-6107-failed/jnnx886qnxc0j47q.txt:[00:44:50] AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n588644c/appveyor-6107-failed/n409j3f11lr50im0.txt:[00:32:40]     assert_in('pickaboo', cml.out)\r\n588644c/appveyor-6107-failed/n409j3f11lr50im0.txt:[00:32:40] AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n588644c/appveyor-6107-failed/p28vcoblx377qwwi.txt:[00:43:45]     assert_in('pickaboo', cml.out)\r\n588644c/appveyor-6107-failed/p28vcoblx377qwwi.txt:[00:43:45] AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/1.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/1.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/2.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/2.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/3.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/3.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/6.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/6.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/7.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/7.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\nde982c5/travis-12020-failed/8.txt:    assert_in('pickaboo', cml.out)\r\nde982c5/travis-12020-failed/8.txt:AssertionError: 'pickaboo' not found in '[WARNING] Failed to import module verycustomrogue__ due to \\n'\r\n```\r\nso I guess it was not that clean", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5758/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5758/timeline", "performed_via_github_app": null}